### ISSUE TITLE
Make mobile-friendly

### ISSUE THREAD

**Issue by waldyrious** [browserpad/browserpad#11]

**Comment by waldyrious** [comment]
From [css-tricks](https://css-tricks.com/snippets/html/responsive-meta-tag/):
```html
<meta name="viewport" content="width=device-width, initial-scale=1" />
```
Don't forget to make all text, links and buttons large enough to be clicked on. perhaps using media queries -- something like:
```css
@media (max-width: 40rem) { html { font-size: 120%; } }
```
